### ISSUE TITLE
pkj review: check if version num matches filename

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-packajoozle#41]
Is it reasonable to check if the version number in DESCRIPTION, configure.ac (if present) matches the file name?

**Comment by apjanke** [comment]
Done in https://github.com/apjanke/octave-packajoozle/commit/87b72c101b79e249b96274aca4a71814b7b8c97f. This verifies that the file name matches the name & version defined in `DESCRIPTION`.

It's already separately verifying that the version in `configure.ac` matches the version in `DESCRIPTION`. It's not checking the name in `configure.ac` because I found that doesn't match the name in some `DESCRIPTION`s, so I didn't know if it was required. Should we require that?

**Comment by lostbard** [comment]
Currently the check for the configure.ac version requires a space after the command, preceding the version number.
AC_INIT([package], [1.0.0]) - will work
AC_INIT([package],[1.0.0]) - will say the version doesn't match

**Comment by apjanke** [comment]
> Currently the check for the configure.ac version requires a space after the command, preceding the version number.

Fixed in https://github.com/apjanke/octave-packajoozle/commit/577b42f5ca6605e42c344a9ff9d20b548b0daf20?

**Comment by lostbard** [comment]
Note, currently for the configure.ac, the check is dependent on there being a space in the AC_INIT statement:

AC_INIT([package], [1.0.0]) - will get a valid version
AC_INIT([package],[1.0.0]) - will not get the version

**Comment by lostbard** [comment]
yep that did it!

**Comment by apjanke** [comment]
Closing as fixed.
